import type { Metadata } from 'next'
import { Pixelify_Sans, Roboto } from 'next/font/google'
import './globals.css'
import { PreloadProvider } from '@/providers/PreloadProvider'

const pixels = Pixelify_Sans({
  subsets: ['latin-ext'],
  weight: ['400', '700'],
  variable: '--font-pixels',
})

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${pixels.variable} ${roboto.variable} bg-zinc-100 overflow-x-hidden`}
      >
        <PreloadProvider>{children}</PreloadProvider>
      </body>
    </html>
  )
}
